version: '2'

services:
  redis:
    image: redis:4
    container_name: sedaily-redis
    restart: always
  sedaily-api:
    image: softwaredaily/sedaily-rest-api:develop
    container_name: sedaily-rest-api
    ports:
      - "4040:4040"
    depends_on:
      - mongo
      - redis
    restart: always
  mongo:
    image: softwaredaily/sedaily-mongo:develop
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
